### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: Collection was modified

### ISSUE THREAD

**Issue by anatoliy-d-plat4me** [sipsorcery-org/sipsorcery#902]
Hello, We're using sipsorcery v6.0.11 on a Linux machine and .net 6.0

We have faced the following exception:

```c#
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at [SIPSorcery.Net](http://sipsorcery.net/).RtpIceChannel.get_RTO()
   at [SIPSorcery.Net](http://sipsorcery.net/).RtpIceChannel.<ProcessChecklist>b__110_2(ChecklistEntry x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at [SIPSorcery.Net](http://sipsorcery.net/).RtpIceChannel.ProcessChecklist()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Maybe you will have opportunities to look at this issue.

Thanks

**Comment by jimm98y** [comment]
I am facing the same issue on Windows 11 ARM64. It happens randomly and looking at the code, I think it could be easily fixed by creating a copy of the lists.

**Comment by giovanelli-michele** [comment]
Hello everyone,
we still faced this issue. We're using SipSorcery version 6.2.4

Here's the exception:

```
Collection was modified; enumeration operation may not execute.
        at System.Collections.Generic.List1.Enumerator.MoveNextRare()
        at System.Linq.Enumerable.WhereListIterator1.MoveNext()
	at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable1 source, Boolean& found)
	at SIPSorcery.Net.RtpIceChannel.ProcessChecklist()
	at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
	at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Looking at the code, I think that line 1585 should be changed the same way as done in #924, specifically

```cs
if (Checklist.Count > 0)
```

instead of 

```cs
if (_checklist.Count > 0)
```

Do you have a chance to check this issue? 

Thank you
